# CircleCI (https://circleci.com) Build Configuration
# NeoGames
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout

      # Add special stuff
      - run: wget https://assets.neogamesmc.net/server/1-11-R1/paper.jar
      - run: script/add-locally.sh com.destroystokyo paper 1.11.2-R1 paper.jar
      - run: wget -O waterfall.jar https://ci.aquifermc.org/job/Waterfall/lastSuccessfulBuild/artifact/Waterfall-Proxy/bootstrap/target/Waterfall.jar
      - run: script/add-locally.sh com.destroystokyo waterfall 1.11-R1 waterfall.jar

      # Download and cache dependencies
      - restore_cache:
          keys:
          - r1-dependencies-{{ checksum "pom.xml" }}
          # fallback to using the latest cache if no exact match is found
          - r1-dependencies-

      - run: mvn dependency:go-offline install -P +build-defaults

      - save_cache:
          paths:
            - ~/.m2
          key: r1-dependencies-{{ checksum "pom.xml" }}